name: Check code style

on: [push]

jobs:
  check-python-code-style:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install black flake8 mypy

      - name: Check flake8 compliance
        run: flake8

      - name: Check Black compliance
        run: black --check .

      - name: Check mypy compliance
        run: mypy